### PR TITLE
Bugfix: Check min max versus current value

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
Closes https://github.com/pyapp-kit/superqt/issues/220

As suggested by Grzegorz here https://github.com/pyapp-kit/superqt/issues/220#issuecomment-1824785806 in this PR I have setMin and setMax check versus the current value and if that is smaller/larger it's reset to min/max.

I also added a test for the issue that fails on current main, but passes with this fix.

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
@Czaki also suggested:
> it could be nice to add check if minimum is lower than maximum in setRange

So this is the case where someone does setRange(100, 0) or similar.
In this case is it better to raise a ValueError or just swap min and max so they are correct?

**Comment by goanpeca** [comment]
Let's do what Qt does for it

https://doc.qt.io/qt-6/qabstractslider.html#setRange

>If max is smaller than min, min becomes the only legal value.

Juste teste with QSlider and there seems to be no error, but the widget becomes invisible, I guess because min. and max become the same.

Swapping would be unexpected behavior so I suggest we either follow what Qt does, (puts min and max equal to min?) or raise a value error.

I would prefer the later, not sure what others think :)

**Comment by psobolewskiPhD** [comment]
I was also leaning towards ValueError.
Can then use `with pytest.raises(ValueError):` to test.

**Review by Czaki — APPROVED** [review]

**Review by tlambert03 — APPROVED** [review]
fantastic.  thanks @psobolewskiPhD!

**Pull request merged**
